### ISSUE TITLE
RPC events crash the server

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#115]
Using RPC events makes the server crash without catching an error. The server just crashes. I've tested similar code on v1 and everything works. It only seems to crash on v2, unless I'm doing it wrong?

### Reproduction

1. Create a client with this code: 
```js
import * as alt from '@altv/client';

alt.log('client loaded');

alt.Events.onConsoleCommand(async({ command, args }) => {
    if(command !== 'rpc') return;
    try {
        const result = await alt.RPC.send("testRPC");
        alt.log("Rpc result:", result);

    } catch (err) {
        alt.logError(`Failed to call rpc: ${err}`);
    }
});
```
2. Create a server with this code:
```js
import * as alt from '@altv/server';

alt.RPC.register('testRPC',  (player, myArg) => {
    return 'My dog is crazydog';
});
```
3. Type ``rpc`` in client console

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/7fbac53b2e6c69106b4751f6138ba49a7dd29a10 - re-test with `dev/0.0-dev29` or later

**Comment by FlorianV85** [comment]
> Fixed in [7fbac53](https://github.com/altmp/altv-js-module-v2/commit/7fbac53b2e6c69106b4751f6138ba49a7dd29a10) - re-test with `dev/0.0-dev29` or later

I've built with the latest commits and it's still crashing. But works well with the latest release. Thinks it's been broken again in the new commits 👀
