### ISSUE TITLE
alt.Vehicle constructor without parameters doesn't throw error (v1 compat)

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#196]
```js
alt.log(1)
new alt.Vehicle()
alt.log(2)
```

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/d00e919e-8867-4657-b08b-005bed0aef57)

**Comment by xLuxy** [comment]
Fixed in `dev/0.0.0-dev.25` (see https://github.com/altmp/altv-js-module-v2/commit/8222ae0c65dbf6803ae60c9a549f78ea39753ad7)

**Comment by xxshady** [comment]
still happens

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/95215711-cf7a-4758-b325-6d514e63305c)

**Comment by Yiin** [comment]
Because both v2 and compatibility uses the same factory class for entities it's not fixable.

`alt.*.create` calls constructor with no args internally to create the object.

There is no sane way to check if the constructor is called using `alt.*.create` or `new alt.*`, hence we don't know if the constructor was called internally when using `alt.*.create` or if it was called directly using `new alt.*`.

**Comment by xxshady** [comment]
there is at least one way to check

**Comment by xxshady** [comment]
its fixable by setting prototype in this [call](https://github.com/altmp/altv-js-module-v2/blob/8e76bba4dcd91c8adc8b2a65c7f6ec6b2c5f074c/shared/src/interfaces/IScriptObjectHandler.cpp#L22) instead of calling [NewInstance](https://github.com/altmp/altv-js-module-v2/blob/8e76bba4dcd91c8adc8b2a65c7f6ec6b2c5f074c/shared/src/ScriptObject.cpp#L22), but we won't change (at least for now) it as it would break factory API
